name: Tests
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Run unit tests with coverage (statements + branches)
        run: |
          pytest -q --maxfail=1 \
            --cov=database --cov=handlers --cov=services \
            --cov-branch \
            --cov-report=term-missing \
            --cov-report=html

      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov
